apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  # replicas:  Number of pods that we want to create running some particular image.
  replicas: 1
  # selector : take a look at all the pods that are created, find all the pods with the label of app: posts
  selector:
    matchLabels:
      app: posts
  # template: is where we specify the extact configuration of a pod that we want this deployment to create.
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: kadweyvaibhav/posts:latest
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
